[build]
  publish = "public/"
  command = "yarn && yarn build"

[[redirects]]
  from = "/assets"
  to = "/:content_id/:unique_id.json"
  query = {content_id = ":content_id", unique_id = ":unique_id"}
  status = 200
  force = true
