[build]
  publish = "public/"
  command = "yarn && yarn build"

[[redirects]]
  from = "/assets"
  to = "/contents/assets.json"
  status = 200
  force = true

[[redirects]]
  from = "/assets/tataminin"
  to = "/contents/tataminin/assets.json"
  status = 200
  force = true

[[redirects]]
  from = "/assets/tataminin/:unique_id"
  to = "/contents/tataminin/:unique_id.json"
  status = 200
  force = true
