swagger: "2.0"
info:
  version: "1.0.0"
  title: "ERC721 Metadata API Speficication"
host: "erc721.netlify.app/metadata"
schemes:
  - "https"
paths:
  /contents:
    get:
      summary: "contents"
      responses:
        "200":
          description: "Secucess"
          schema:
            type: "object"
            properties:
              [content_id]:
                schema:
                type: "array"
                items:
                  $ref: "#/definitions/Metadata"
  /contents/{content_id}/:
    get:
      summary: "contents/{content_id}"
      responses:
        "200":
          description: "Secucess"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Metadata"
  /contents/{content_id}/{unique_Id}:
    get:
      summary: "contents/{content_id}/{unique_Id}"
      responses:
        "200":
          description: "Secucess"
          schema:
            $ref: "#/definitions/Metadata"
definitions:
  Metadata:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      description:
        type: "string"
      external_url:
        type: "string"
      image:
        type: "string"
    xml:
      name: "Order"
