swagger: "2.0"
info:
  version: "1.0.0"
  title: "ERC721 Metadata API Speficication"
host: "erc721.netlify.app"
schemes:
  - "https"
paths:
  /assets:
    get:
      summary: "Assets"
      description: "Get Assets Metadata"
      parameters:
        - in: "query"
          type: "string"
          name: "content_id"
        - in: "query"
          type: "string"
          name: "unique_id"
      responses:
        "200":
          description: "Secucess"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Metadata"
definitions:
  Metadata:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      description:
        type: "string"
      external_url:
        type: "string"
      image:
        type: "string"
    xml:
      name: "Order"
